### ISSUE TITLE
Sugar orm 공부 자료 찾기!

### ISSUE THREAD

**Issue by jieunhong** [jieunhong/GoTogther2016#11]

**Comment by DaHoe34** [comment]
http://humble.tistory.com/13

**Comment by jieunhong** [comment]
http://stackoverflow.com/questions/32155729/how-to-use-sugar-orm

**Comment by DaHoe34** [comment]
http://blog.naver.com/dolking1234/220075423906

**Comment by jieunhong** [comment]
http://satyan.github.io/sugar/index.html
