### ISSUE TITLE
이슈 사용법 연습 - 프로젝트 관리 페이지 작성

### ISSUE THREAD

**Issue by progh2** [jieunhong/GoTogther2016#3]
- [x] 깃허브에 프로젝트 만들기

- [x] 가입 멤버 추가시키

- [x] 마일스톤, 이슈 사용법 익히게 하기

- [x] 프로젝트의 마일스톤, 이슈 추가하게 하기 

![image](https://cloud.githubusercontent.com/assets/1307187/18428846/4c3d613a-790b-11e6-84fe-e280bab3491e.png)

**Comment by progh2** [comment]
설명 다들 잘 들었고 프로젝트 잘 써보기를!!

**Comment by jieunhong** [comment]
넹 알겠습니다 :)
